### PR TITLE
fix(#50): fastify decorator warning

### LINKED ISSUE #50: FastifyDeprecation: Use onRequest hook instead
```
import auth0Verify from 'fastify-auth0-verify';
server.register(auth0Verify, {
    domain: "...",
  });
```
Yields this warning:

FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: auth0Verify

Anyone following the readme and using:

```
    "fastify": "^3.2.1",
```

Might encounter this.

### PR DESCRIPTION
**Pull request by salmanm**
Fixes #50

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -195,15 +195,21 @@ function fastifyAuth0Verify(instance, options, done) {
 
     // Setup our decorators
     instance.decorate('authenticate', authenticate)
-    instance.decorate('auth0Verify', auth0Options)
-    instance.decorateRequest('auth0Verify', auth0Options)
+    instance.decorate('auth0Verify', {
+      getter: () => auth0Options
+    })
```
Comment (mcollina) [inline index.js:200]: I don't think this is needed. Can you check?

Comment (salmanm) [reply index.js]: Ah good catch, removed.

**Review by mcollina — APPROVED** [review]
lgtm
